name: "Infer Chat"
description: "Chat with LLM model"
author: "JingleManSweep"

inputs:
  openai_api_key:
    description: "OpenAI API Key"
    required: true
  embedding_model:
    description: "OpenAI Embedding model name"
    required: false
    default: "text-embedding-ada-002"
  supabase_url:
    description: "Supabase instance URL"
    required: true
  supabase_key:
    description: "Supabase service role key"
    required: true
  supabase_table:
    description: "Supabase table name"
    required: true
  supabase_collection:
    description: "Supabase collection name"
    required: true
  rag_prompt:
    description: "RAG prompt"
    required: false
    default: "rlm/rag-prompt"
  chat_model:
    description: "LLM chat model name"
    required: false
    default: "gpt-3.5-turbo"
  prompt_text:
    description: "Query text to search in the RAG system"
    required: true

runs:
  using: docker
  image: ghcr.io/jinglemansweep/rag-actions:latest
  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    EMBEDDING_MODEL: ${{ inputs.embedding_model }}
    SUPABASE_URL: ${{ inputs.supabase_url }}
    SUPABASE_KEY: ${{ inputs.supabase_key }}
    SUPABASE_TABLE: ${{ inputs.supabase_table }}
    SUPABASE_COLLECTION: ${{ inputs.supabase_collection }}
    CHAT_MODEL: ${{ inputs.chat_model }}
    PROMPT_TEXT: ${{ inputs.prompt_text }}
  args: ["-m", "rag_action.infer.chat"]
