name: "Ingest Loader"
description: "Loads content from a various sources"
author: "JingleManSweep"

inputs:
  openai_api_key:
    description: "OpenAI API Key"
    required: true
  embedding_model:
    description: "OpenAI Embedding model name"
    required: false
    default: "text-embedding-ada-002"
  supabase_url:
    description: "Supabase instance URL"
    required: true
  supabase_key:
    description: "Supabase service role key"
    required: true
  supabase_table:
    description: "Supabase table name"
    required: true
  loader_class:
    description: "Loader class for reading files"
    required: false
    default: "markdown"
  loader_options:
    description: "Options for the loader class"
    required: false
    default: "{}"
  chunk_class:
    description: "Chunk class for text splitting"
    required: false
    default: "RecursiveCharacterTextSplitter"
  chunker_options:
    description: "Options for the chunker class"
    required: false
    default: "{}"
  metadata:
    description: "Metadata for the ingestion"
    required: false
    default: "{}"

runs:
  using: docker
  image: ../../../Dockerfile
  # image: docker://ghcr.io/jinglemansweep/rag-actions:main

  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    EMBEDDING_MODEL: ${{ inputs.embedding_model }}
    SUPABASE_URL: ${{ inputs.supabase_url }}
    SUPABASE_KEY: ${{ inputs.supabase_key }}
    SUPABASE_TABLE: ${{ inputs.supabase_table }}
    CHUNK_SIZE: ${{ inputs.chunk_size }}
    CHUNK_OVERLAP: ${{ inputs.chunk_overlap }}
    DIRECTORY: ${{ inputs.directory }}
    GLOB_PATTERN: ${{ inputs.glob_pattern }}
    METADATA: ${{ inputs.metadata }}
  args: ["-m", "rag_action.ingest.directory"]
