name: "Ingest Loader"
description: "Loads content from a various sources"
author: "JingleManSweep"

inputs:
  openai_api_key:
    description: "OpenAI API Key"
    required: true
  embedding_model:
    description: "OpenAI Embedding model name"
    required: false
    default: "text-embedding-ada-002"
  supabase_url:
    description: "Supabase instance URL"
    required: true
  supabase_key:
    description: "Supabase service role key"
    required: true
  supabase_table:
    description: "Supabase table name"
    required: true
  metadata:
    description: "Metadata for the ingestion"
    required: false
    default: "{}"
  args:
    description: "General arguments"
    required: false
    default: '{}'
  loader_class:
    description: "Loader class"
    required: false
    default: "markdown"
  loader_args:
    description: "Loader arguments"
    required: false
    default: "{}"
  chunker_class:
    description: "Chunker class"
    required: false
    default: "recursive_character"
  chunker_args:
    description: "Chunker arguments"
    required: false
    default: '{"chunk_size": 1000, "chunk_overlap": 200}'


runs:
  using: docker
  image: ../../../Dockerfile
  # image: docker://ghcr.io/jinglemansweep/rag-actions:main

  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    EMBEDDING_MODEL: ${{ inputs.embedding_model }}
    SUPABASE_URL: ${{ inputs.supabase_url }}
    SUPABASE_KEY: ${{ inputs.supabase_key }}
    SUPABASE_TABLE: ${{ inputs.supabase_table }}
    METADATA: ${{ inputs.metadata }}
    ARGS: ${{ inputs.args }}
    LOADER_CLASS: ${{ inputs.loader_class }}
    LOADER_ARGS: ${{ inputs.loader_args }}
    CHUNKER_CLASS: ${{ inputs.chunker_class }}
    CHUNKER_ARGS: ${{ inputs.chunker_args }}
  args: ["-m", "rag_action.ingest.loader"]
