name: "RAG Query Template"
description: "Render Jinja templates using results from RAG query"
author: "JingleManSweep"

inputs:
  openai_api_key:
    description: "OpenAI API Key"
    required: true
  embedding_model:
    description: "OpenAI Embedding model name"
    required: false
    default: "text-embedding-ada-002"
  supabase_url:
    description: "Supabase instance URL"
    required: true
  supabase_key:
    description: "Supabase service role key"
    required: true
  supabase_table:
    description: "Supabase table name"
    required: true
  supabase_collection:
    description: "Supabase collection name"
    required: true
  state_json:
    description: "JSON state from previous steps"
    required: false
    default: "{}"

runs:
  using: docker
  image: docker://ghcr.io/jinglemansweep/rag-actions:main
  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    EMBEDDING_MODEL: ${{ inputs.embedding_model }}
    SUPABASE_URL: ${{ inputs.supabase_url }}
    SUPABASE_KEY: ${{ inputs.supabase_key }}
    SUPABASE_TABLE: ${{ inputs.supabase_table }}
    SUPABASE_COLLECTION: ${{ inputs.supabase_collection }}
    STATE_JSON: ${{ inputs.state_json }}
  args: ["-m", "rag_action.query.test"]
