name: "RAG Directory Ingest"
description: "Loads content from a directory, chunks, creates embeddings, stores in Supabase"
author: "JingleManSweep"

inputs:
  openai_api_key:
    description: "OpenAI API Key"
    required: true
  embedding_model:
    description: "OpenAI Embedding model name"
    required: false
    default: "text-embedding-ada-002"
  supabase_url:
    description: "Supabase instance URL"
    required: true
  supabase_key:
    description: "Supabase service role key"
    required: true
  supabase_table:
    description: "Supabase table name"
    required: true
  chunk_size:
    description: "Chunk size for text splitting"
    required: false
    default: "500"
  chunk_overlap:
    description: "Chunk overlap for text splitting"
    required: false
    default: "50"
  ingest_dir:
    description: "Content ingestion directory"
    required: true
  ingest_metadata:
    description: "Metadata for the ingestion"
    required: false
    default: "{}"

runs:
  using: docker
  image: ../../../Dockerfile
  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    EMBEDDING_MODEL: ${{ inputs.embedding_model }}
    SUPABASE_URL: ${{ inputs.supabase_url }}
    SUPABASE_KEY: ${{ inputs.supabase_key }}
    SUPABASE_TABLE: ${{ inputs.supabase_table }}
    CHUNK_SIZE: ${{ inputs.chunk_size }}
    CHUNK_OVERLAP: ${{ inputs.chunk_overlap }}
    INGEST_DIR: ${{ inputs.ingest_dir }}
    INGEST_METADATA: ${{ inputs.ingest_metadata }}
  args: ["-m", "rag_action.ingest.directory"]
