name: "Example Workflow"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:

  IngestSkills:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Ingest Directory
        id: ingest_skills
        uses: jinglemansweep/rag-actions/.github/actions/ingest-directory@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          supabase_url: ${{ secrets.SUPABASE_URL }}
          supabase_key: ${{ secrets.SUPABASE_KEY }}
          supabase_table: ${{ vars.SUPABASE_TABLE }}
          supabase_collection: "${{ vars.SUPABASE_COLLECTION }}_example"
          ingest_dir: "./test/content/skills/devops"
          ingest_metadata: '{"category": "devops"}'

  QuerySearchDevOps:
    runs-on: ubuntu-latest
    needs:
      - IngestSkills
    outputs:
      json: ${{ steps.main.outputs.json }}
    steps:

      - name: Query Search
        id: main
        uses: jinglemansweep/rag-actions/.github/actions/query-search@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          supabase_url: ${{ secrets.SUPABASE_URL }}
          supabase_key: ${{ secrets.SUPABASE_KEY }}
          supabase_table: ${{ vars.SUPABASE_TABLE }}
          supabase_collection: "${{ vars.SUPABASE_COLLECTION }}_example"
          query_text: "devops"
          top_k: "3"

  InferChat:
    runs-on: ubuntu-latest
    needs:
      - QuerySearchDevOps
    outputs:
      json: ${{ steps.main.outputs.json }}
    steps:

      - name: Infer Chat
        id: main
        uses: jinglemansweep/rag-actions/.github/actions/infer-chat@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          supabase_url: ${{ secrets.SUPABASE_URL }}
          supabase_key: ${{ secrets.SUPABASE_KEY }}
          supabase_table: ${{ vars.SUPABASE_TABLE }}
          supabase_collection: "${{ vars.SUPABASE_COLLECTION }}_example"
          prompt_text: |
            ${{ vars.PROMPT_RAG }}
            ${{ needs.QuerySearchDevOps.outputs.json }}

  ChatOutput:
    runs-on: ubuntu-latest
    needs:
      - InferChat
    steps:

      - name: Output
        id: main
        run: |
          echo '${{ needs.InferChat.outputs.json }}''


  QueryTest1:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.main.outputs.json }}
    steps:

      - name: Query Test
        id: main
        uses: jinglemansweep/rag-actions/.github/actions/query-test@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          supabase_url: ${{ secrets.SUPABASE_URL }}
          supabase_key: ${{ secrets.SUPABASE_KEY }}
          supabase_table: ${{ vars.SUPABASE_TABLE }}
          supabase_collection: "${{ vars.SUPABASE_COLLECTION }}_example"
          json: '{"query": "devops"}'

  QueryTest2:
    runs-on: ubuntu-latest
    needs:
      - QueryTest1
    outputs:
      json: ${{ steps.main.outputs.json }}
    steps:

      - name: Query Test
        id: main
        uses: jinglemansweep/rag-actions/.github/actions/query-test@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          supabase_url: ${{ secrets.SUPABASE_URL }}
          supabase_key: ${{ secrets.SUPABASE_KEY }}
          supabase_table: ${{ vars.SUPABASE_TABLE }}
          supabase_collection: "${{ vars.SUPABASE_COLLECTION }}_example"
          json: ${{ needs.QueryTest1.outputs.json }}
