name: "Example Workflow"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  IngestDirectorySkills:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Directory Ingestion
        uses: jinglemansweep/rag-actions/.github/actions/ingest-directory@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          supabase_url: ${{ secrets.SUPABASE_URL }}
          supabase_key: ${{ secrets.SUPABASE_KEY }}
          supabase_table: ${{ vars.SUPABASE_TABLE }}
          supabase_collection: "${{ vars.SUPABASE_COLLECTION }}_skills"
          ingest_dir: "./test/content/skills"

  QueryTemplateSkills:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Query Template
        id: query_template
        uses: jinglemansweep/rag-actions/.github/actions/query-template@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          supabase_url: ${{ secrets.SUPABASE_URL }}
          supabase_key: ${{ secrets.SUPABASE_KEY }}
          supabase_table: ${{ vars.SUPABASE_TABLE }}
          supabase_collection: "${{ vars.SUPABASE_COLLECTION }}_skills"
          query_text: "DevOps"
          top_k: "3"
          template_text: |
            You are a helpful assistant that provides information about a candidate's skills. The candidate has the following skills:

            <skills>
            {% for doc in docs %}
              <skill>
                {{ doc.page_content }}
              </skill>
            {% endfor %}
            </skills>
      - name: Template Output
        run: |
          echo "${{ steps.query_template.outputs.text }}"
