name: "Example Workflow"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:

  QueryTest1:
    runs-on: ubuntu-latest
    outputs:
      state: ${{ steps.main.outputs.state }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Query Test
        id: main
        uses: jinglemansweep/rag-actions/.github/actions/query-test@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          supabase_url: ${{ secrets.SUPABASE_URL }}
          supabase_key: ${{ secrets.SUPABASE_KEY }}
          supabase_table: ${{ vars.SUPABASE_TABLE }}
          supabase_collection: "${{ vars.SUPABASE_COLLECTION }}_example"
          state_json: '{"inputs": {"query": "devops"}}'

  QueryTest2:
    runs-on: ubuntu-latest
    needs:
      - QueryTest1
    outputs:
      state: ${{ steps.main.outputs.state }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Query Test
        id: main
        uses: jinglemansweep/rag-actions/.github/actions/query-test@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          supabase_url: ${{ secrets.SUPABASE_URL }}
          supabase_key: ${{ secrets.SUPABASE_KEY }}
          supabase_table: ${{ vars.SUPABASE_TABLE }}
          supabase_collection: "${{ vars.SUPABASE_COLLECTION }}_example"
          state_json: ${{ needs.QueryTest1.outputs.state }}
