name: "Tests: Ingestion"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:

  IngestionTests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Directory Ingestion
        uses: jinglemansweep/rag-actions/.github/actions/ingest-loader@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          supabase_url: ${{ secrets.SUPABASE_URL }}
          supabase_key: ${{ secrets.SUPABASE_KEY }}
          supabase_table: ${{ vars.SUPABASE_TABLE }}
          metadata: |
            {
              "collection": "${{ vars.SUPABASE_COLLECTION }}",
              "github": {
                "run": "${{ github.run_id }}"
              }
            }
          args: |
            {
              "path": "./test/content/test",
              "glob": "**/*.md"
            }
          loader_class: "markdown"
          loader_args: '{}'
          chunker_class: "recursive_character"
          chunker_args: '{"chunk_size": 1000, "chunk_overlap": 200}'

      - name: RSS Feed Ingestion
        uses: jinglemansweep/rag-actions/.github/actions/ingest-loader@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          supabase_url: ${{ secrets.SUPABASE_URL }}
          supabase_key: ${{ secrets.SUPABASE_KEY }}
          supabase_table: ${{ vars.SUPABASE_TABLE }}
          metadata: |
            {
              "collection": "${{ vars.SUPABASE_COLLECTION }}",
              "feed": "news",
              "source": "bbc",
              "github": {
                "run": "${{ github.run_id }}"
              }
            }
          loader_class: "rss"
          loader_args: |
            {
              "urls": [
                "https://feeds.bbci.co.uk/news/rss.xml"
              ]
            }


      - name: Web Page Ingestion
        uses: jinglemansweep/rag-actions/.github/actions/ingest-loader@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          supabase_url: ${{ secrets.SUPABASE_URL }}
          supabase_key: ${{ secrets.SUPABASE_KEY }}
          supabase_table: ${{ vars.SUPABASE_TABLE }}
          metadata: |
            {
              "collection": "${{ vars.SUPABASE_COLLECTION }}",
              "source": "web",
              "github": {
                "run": "${{ github.run_id }}"
              }
            }
          loader_class: "web"
          loader_args: |
            {
              "web_path": "https://www.bbc.co.uk"
            }
