name: "Actions Test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  IngestDirectory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run RAG Indexer Action (Directory Ingestion)
        uses: jinglemansweep/rag-actions/.github/actions/rag-indexer@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          supabase_url: ${{ secrets.SUPABASE_URL }}
          supabase_key: ${{ secrets.SUPABASE_KEY }}
          supabase_table: "documents"
          ingest_dir: "./test/content"
          ingest_metadata: '{"github": {"run": "${{ github.run_id }}"}}'

  IngestText:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run RAG Indexer Action (Text Ingestion)
        uses: jinglemansweep/rag-actions/.github/actions/rag-indexer@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          supabase_url: ${{ secrets.SUPABASE_URL }}
          supabase_key: ${{ secrets.SUPABASE_KEY }}
          supabase_table: "documents"
          ingest_text: |
            This is a test text to be ingested into the RAG system.
            It will be chunked and stored in the Supabase database.
            GitHub Run ID: ${{ github.run_id }}
          ingest_metadata: '{"github": {"run": "${{ github.run_id }}"}}'
