name: "LangChain RAG Indexer"
description: "Loads text or webpages, chunks, creates embeddings, stores in Supabase"
author: "JingleManSweep"

inputs:
  openai_api_key:
    description: "OpenAI API Key"
    required: true
  embedding_model:
    description: "OpenAI Embedding model name"
    required: false
    default: "text-embedding-ada-002"
  supabase_url:
    description: "Supabase instance URL"
    required: true
  supabase_key:
    description: "Supabase service role key"
    required: true
  supabase_table:
    description: "Supabase table name"
    required: false
    default: "rag_chunks"
  chunk_size:
    description: "Chunk size for text splitting"
    required: false
    default: "500"
  chunk_overlap:
    description: "Chunk overlap for text splitting"
    required: false
    default: "50"
  docs_dir:
    description: "Directory containing documents"
    required: false
    default: ""
  url:
    description: "URL to crawl"
    required: false
    default: ""

runs:
  using: docker
  image: ../../../Dockerfile
  env:
    OPENAI_API_KEY: ${{ inputs.openai_api_key }}
    EMBEDDING_MODEL: ${{ inputs.embedding_model }}
    SUPABASE_URL: ${{ inputs.supabase_url }}
    SUPABASE_KEY: ${{ inputs.supabase_key }}
    SUPABASE_TABLE: ${{ inputs.supabase_table }}
    CHUNK_SIZE: ${{ inputs.chunk_size }}
    CHUNK_OVERLAP: ${{ inputs.chunk_overlap }}
    DOCS_DIR: ${{ inputs.docs_dir }}
    URL: ${{ inputs.url }}